---
# defaults file for rke

#
rke_version:

#
#rke_packages:

#
rke_dependencies:
  - container-selinux
  - rke2-common
  - rke2-selinux
  #- rke2-server
  - iptables
  - libnetfilter_conntrack
  - libnfnetlink
  - libnftnl
  - ipvsadm
  - policycoreutils-python-utils

#
rke_configuration_directories:
  - /etc/rancher/rke2
  - /var/lib/rancher/rke2/agent/images/








