---
galaxy_info:
  author: itscturner
  role_name: authorized_key
  description: An ansible role to configure authorized keys.
  license: Apache-2.0
  min_ansible_version: "2.12"

  platforms:
    - name: RHEL
      versions:
        - "9"

  galaxy_tags:
    - ssh
    - user

  dependencies: []
