# Tasks file debug

- name: Collect package facts
  ansible.builtin.package_facts:

- name: Collect service facts
  ansible.builtin.service_facts:

- name: Show variables
  ansible.builtin.debug:
    var: vars
